### ISSUE TITLE
Drupal 8 branch

### ISSUE THREAD

**Issue by jhedstrom** [Gizra/message_notify#11]
I've started a D8 port here: https://github.com/jhedstrom/message_notify

Once that is a bit further along, it would be good to have an 8.x branch here so PRs can be opened and reviewed.

**Comment by amitaibu** [comment]
@jhedstrom you are awesome! :wink: 

Sure, open a PR and we can get it here (branch name should be `8.x-1.x`, though)

**Comment by jhedstrom** [comment]
I've made a bit more progress. I have dedicated time this week and next to work on this, so I'll try to get a PR together soon. I've renamed the branch to `8.x-1.x`. Can you cut a branch here by the same name so the PR doesn't go against 7.x?

**Comment by amitaibu** [comment]
:+1: 

> Can you cut a branch here by the same name so the PR doesn't go against 7.x

You mean something like [this](https://github.com/Gizra/message_notify/tree/8.x-1.x)?
