### ISSUE TITLE
Cut an alpha release and push 8.x back to drupal.org

### ISSUE THREAD

**Issue by jhedstrom** [Gizra/message_notify#15]
I think the current state of the module is capable of being called an alpha. It would be nice to add a release and push up to drupal.org for greater visibility.

Thanks!

**Comment by amitaibu** [comment]
I had a look, and there's a lot of more work to be done here. In fact, there's still D7 code, and no test or example on how to actually send a message.

So I think better to postpone this for now.

**Comment by amitaibu** [comment]
Sorry, I see there are a few tests under [src/Tests](https://github.com/Gizra/message_notify/tree/8.x-1.x/src/Tests). We should probably move them to `/tests`.

After that we can delete the exmaple module until it's ported, and then we can have a first alpha.

**Comment by amitaibu** [comment]
(Luckily we have a client site that use this module, so I hope to get @savyoncohen to send a few quality PRs 😄 )

**Comment by jhedstrom** [comment]
I added #26 for the remaining work.

**Comment by jhedstrom** [comment]
I've added a beta milestone for tracking further steps. I'm cutting an alpha release now.

**Comment by amitaibu** [comment]
Thanks for doing it - and so fast! Are you going to be in DrupalCon?

**Comment by jhedstrom** [comment]
Sadly, I'll be missing DrupalCon Europe this year. I'd hoped to catch up with you!
