### ISSUE TITLE
MessageNotifierInterface should extend PluginInspectionInterface and DerivativeInspectionInterface

### ISSUE THREAD

**Issue by jhedstrom** [Gizra/message_notify#33]
Since `MessageNotifyBase` extends `PluginBase`, it might as well extend the 2 interfaces that `PluginBase` implements:
1. `PluginInspectionInterface`
2. `DerivativeInspectionInterface`

**Comment by amitaibu** [comment]
Why is that needed - Just as "best practice"?

**Comment by jhedstrom** [comment]
It's not strictly required, but for instance, if I type-hint an alter hook with:

``` php
function foo_alter(MessageNotifierInterface $notifier) { }
```

My IDE won't pick up that `$notifier` has methods provided by those other interfaces (such as `getPluginId()`, even though the actual object passed along _will_ have those methods since it extends `PluginBase`.

**Comment by amitaibu** [comment]
👍
