### ISSUE TITLE
Sending a message to multiple recipients

### ISSUE THREAD

**Issue by pfrenssen** [Gizra/message_notify#58]
What would be the best way to deal with messages that have multiple recipients?

I have to send out a message to a team of moderators when a user reports spam on the site. I am generating a Message entity, and I have a view of all messages of the "Spam report" template that the moderators can use to track which spam is already dealt with.

How can I send this message out to multiple people without generating duplicate Message entities?

**Comment by RoySegall** [comment]
You don't have to save the message to the DB in order to send it. you can pass it as a setting in the notifier handler.

But you might want to take a look on the message subscriber module which created for that - send a lot of messages. You can also take a look on message digest(if there is a D8 branch)

**Comment by amitaibu** [comment]
@pfrenssen ! :)

You have options to not save on fail/ success -- https://github.com/Gizra/message_notify/blob/c590b55a23ad36bff8db789d0bef787b038255c1/src/Plugin/Notifier/MessageNotifierBase.php#L68-L71

**Comment by pfrenssen** [comment]
Thanks for the feedback! So I had a look at both options:

* Message Subscriber is a really fancy way of sending notifications about a message to a group of users. It uses a batch process so it can scale to large numbers of users.
* For a small number of recipients you can clone the Message entity, change the recipient with `$message->setOwner()` or `$message->setOwnerId()` and then send it using the option `['save_on_success' => FALSE]`, without saving the message again.

Since I only have a small team of moderators I will take the second option.

Thanks a lot for the help!
