### ISSUE TITLE
No email sent

### ISSUE THREAD

**Issue by adarshkhatri** [Gizra/message_notify#59]
I am not sure what's happening with my instance. I have got fresh installed 8.3.x drupal site and all message stacks are installed. All example modules are installed too along with token and flag. All flags are enabled  and I have got message subscribed users too.

**When I add content/comment, I can see messages are created in "admin > content > message" section, but no emails are sent.**

Do I need to do more things? I thought by default it should work. All node subscriber should get the email on node update or comment added on that node. Or at least author should get email on each comment added by other users.

Please suggest.

**Comment by usethe23** [comment]
I also have the same problem, and i didn't find any documentation to help.

**Comment by jhedstrom** [comment]
Are you using the `message_subscribe_email` module to enable subscriptions?

If not, adding the email notifier as the default notifier under the message subscribe settings might be the issue...

**Comment by adarshkhatri** [comment]
Yes, all modules of Message stacks are enabled.

**Comment by usethe23** [comment]
For me too i've enabled all the modules and the email notifier is the default notifier.

![capture](https://user-images.githubusercontent.com/275013/27375084-51bda016-566e-11e7-90ed-0ba05e095838.PNG)

**Comment by jhedstrom** [comment]
Now that https://github.com/Gizra/message_subscribe/pull/101 is resolved, I wonder if additional information appears in the logs when debugging is enabled?

**Comment by adarshkhatri** [comment]
I added as per your pull request: `'#default_value' => $config->get('debug_mode')`, and it helped me to save "debugging mode", however I don't see any email sent on comment added. No notifications are sent. 

I must have missed something.

**Comment by usethe23** [comment]
Me too, nothing in the logs.

**Comment by jhedstrom** [comment]
I think the issue is that the message_notify_example module is not ported (#28) and there is no message_subscribe_example module.

**Comment by adarshkhatri** [comment]
Yeah, looks like it is the case. I couldn't find `message_notify_example` module.

**Comment by adarshkhatri** [comment]
@jhedstrom any update? If you could just add the example module `message_notify_example`, that would help a lot.

Thanks.

**Comment by adarshkhatri** [comment]
@jhedstrom I guess I will have to develop the example module.

**Comment by adarshkhatri** [comment]
Till dev team adds their version of message_notify_example, attached file will serve for sending email.
[message_notify_example.zip](https://github.com/Gizra/message_notify/files/1546560/message_notify_example.zip)
