### ISSUE TITLE
MessageNotifierBase calling assert(): Calling assert() with a string argument is deprecated

### ISSUE THREAD

**Issue by amitaibu** [Gizra/message_notify#72]
Continue discussion form https://www.drupal.org/project/message_notify/issues/2966213

**Comment by jhedstrom** [comment]
Should we move development back to drupal.org now that all our testing needs are covered by testbot?

**Comment by amitaibu** [comment]
My reasoning was Travis and PRs. I think that once we'll have gitlab on d.o. we could say goodby to Github. However, since you are really doing the hard work, then I'd say it's your call 😸

**Comment by amitaibu** [comment]
(closing this issue, as discussion is on d.o.)
